#!/bin/bash

# Solid participant

# Run this script in one terminal and the fluid solver in another terminal.

# Use the precice-config for the serial run
ln -s -f precice-configs/precice_config_plate_implicit.xml precice-config.xml


blockMesh -case Solid_convection


laplacianFoam -case Solid_convection
